apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
    - name: liveness
      image: busybox
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 60;
#      livenessProbe:
#        exec:
#          command:
#            - cat
#            - /tmp/healthy
#        initialDelaySeconds: 50
#        periodSeconds: 5