apiVersion: v1
kind: Secret
metadata:
  name: docker-regcred
  namespace: water
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jbi1oYW5nemhvdS5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogIjVhU242WnVFTlRJNE9rTnZiVzF2YmlVeE1qTTBOVFk9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson