---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: zx-web
                port:
                  number: 8080