apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: water
  name: zx-web
  labels:
    app: zx-web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zx-web
      version: v1
  template:
    metadata:
      labels:
        app: zx-web
        version: v1
    spec:
      containers:
      - name: zx-web
        image: registry.cn-hangzhou.aliyuncs.com/k8s_water/zx-web-amd64:latest
        imagePullPolicy: Always
#        resources:
#          limits:
#            cpu: "1"
#            memory: "500Mi"
#          requests:
#            cpu: "0.5"
#            memory: "200Mi"
        ports:
        - containerPort: 8080
        livenessProbe:
          - initialDelaySeconds: 30
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 1
        readinessProbe:
          - initialDelaySeconds: 30
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThredshold: 1
      imagePullSecrets:
        - name: docker-regcred